const Users=[
    {
        "id":"01",
        "tile":"Selena",
        "password":"Selena1234"
    },
    {
        "id":"02",
        "tile":"Aelin",
        "password":"Aelin1234"
    },
    {
        "id":"03",
        "tile":"Manon",
        "password":"Manon1234"
    },
    {
        "id":"04",
        "tile":"Dorian",
        "password":"Dorian1234"
    },
    {
        "id":"05",
        "tile":"Rowan",
        "password":"Rowan1234"
    },
    {
        "id":"06",
        "tile":"Gabriel",
        "password":"Gabriel1234"
    },
    {
        "id":"07",
        "tile":"Lysandra",
        "password":"Lysandra1234"
    }
];
export{ Users};
